# Generated by Django 4.0.4 on 2022-05-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antiquite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.IntegerField()),
                ('peuple', models.CharField(max_length=100)),
                ('evenement_associe', models.CharField(max_length=100)),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoque_appartenance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='antiquite.antiquite')),
            ],
        ),
    ]
